### ISSUE TITLE
[Bug]: Getting Quantity is required. Add `quantity` to `line_items[0]` when not a subscriber

### ISSUE THREAD

**Issue by oliwerhelsen** [maartenpaauw/filament-cashier-billing-provider#20]
### What happened?

Hi,

Getting this(see title) error message when `->requiresTenantSubscription()` is set on a new tenant. 

![image](https://github.com/maartenpaauw/filament-cashier-billing-provider/assets/2570700/5a265de8-270d-4cfb-b62c-4b8f969df938)

### How to reproduce the bug

Follow the documentation for setting up the plugin. Create tenant for a logged in user. Can't create tenant. 

### Package Version

latest

### PHP Version

latest

### Which operating systems does with happen with?

macOS

**Comment by oliwerhelsen** [comment]
My bad. I missconfigured the webhook setup.

**Comment by maartenpaauw** [comment]
No worries! Webhook setups can be tricky sometimes. Let me know if you need further help configuring this plug-in!

**Comment by iammayron** [comment]
I am having this same issue, and I can't figure out how to fix it. 

Could you please help me?

**Comment by maartenpaauw** [comment]
@iammayron im not sure how @oliwerhelsen fixed his issue and what the miss configuration was. Hopefully he can help you out!

**Comment by iammayron** [comment]
I will keep trying today @maartenpaauw, and I will post the solution if I figure that out or if @oliwerhelsen help me out :D

**Comment by oliwerhelsen** [comment]
> I will keep trying today @maartenpaauw, and I will post the solution if I figure that out or if @oliwerhelsen help me out :D

Sorry for late reply @iammayron. Could be something with the running webhook for stripe. Check this docs: https://laravel.com/docs/11.x/billing#handling-stripe-webhooks. I missed this part php artisan cashier:webhook --url "https://example.com/stripe/webhook" with /stripe/webhook. 

Also try to change 'metered_price' => true, to *false*.

Best of luck!

**Comment by iammayron** [comment]
@oliwerhelsen That solved my issue :D 

Thank you very much

@maartenpaauw Just so you know, there may be a bug with the 

```
'metered_price' => true
```

The package does not work when that is active.

**Comment by maartenpaauw** [comment]
Are you sure your price is actually configured as a metered price within Stripe before you change the configuration value to true?

I'm running an application in production with that configuration value configured as true, I'm not entirely sure what the bug must be? Could you clarify it a bit more?

**Comment by maartenpaauw** [comment]
It's also possible to leave the metered_price array key completely away. The package defaults to false when not configured.
