### ISSUE TITLE
[Bug]: Unable to use on with different model than User

### ISSUE THREAD

**Issue by jimiero** [maartenpaauw/filament-cashier-billing-provider#26]
### What happened?

Hello,

Does this package support usage other than User model ? I'm looking to see if I can use it per teams ( Tenant ) model.

### How to reproduce the bug

.

### Package Version

2.X

### PHP Version

8.2

### Which operating systems does with happen with?

macOS

**Comment by matildasmets** [comment]
@jimiero What was the solution to your issue? I have the same issue

**Comment by jimiero** [comment]
@matildasmets i've ended up using something else unfortunately.

**Comment by maartenpaauw** [comment]
This package is, because cashier is not limited, to user model. See: https://laravel.com/docs/12.x/billing

**Comment by matildasmets** [comment]
> This package is, because cashier is not limited, to user model. See: https://laravel.com/docs/12.x/billing

I tried, but got this error when adding the billable method to 'organisatie'
`Filament tenant does not match the Cashier customer model`

**Comment by matildasmets** [comment]
> This package is, because cashier is not limited, to user model. See: https://laravel.com/docs/12.x/billing

Fixed it! 
I added `Cashier::useCustomerModel(Organisatie::class);` to my AppServiceProvider and the billable trait to my model.
