### ISSUE TITLE
[Bug]: Subscription Issue Trials

### ISSUE THREAD

**Issue by Wazzatuts** [maartenpaauw/filament-cashier-billing-provider#27]
### What happened?

Im currently trying to add a trial to my subscription model but its not working as expected its still taking first payment on redirection.

### How to reproduce the bug

In cashier config 

```
 'plans' => [
        'default' => [
            'product_id' => ENV('CASHIER_STRIPE_SUBSCRIPTION_DEFAULT_PRODUCT_ID'),
            'price_id' => ENV('CASHIER_STRIPE_SUBSCRIPTION_DEFAULT_PRICE_ID'),
            'type' => 'default',
            'has_generic_trial' => true,
            'trial_days' => 14,
        ],
    ],
```

Setup products on stripe and match the `product_id` and `price_id`

Add Tenant informaiton in my case it was on 

`CompanyPanelProvider`

```
            ->tenant(Company::class)
            ->tenantBillingProvider(new BillingProvider('default'))
            ->requiresTenantSubscription()
            ->registration(RegisterCompany::class)
            ->tenantRoutePrefix('company');
```

Create a new company as normal on filament, login to new company and gets redirected to stripe payment however without trial just want to take the payment same day 

![image](https://github.com/user-attachments/assets/9c3cf004-a119-478f-a601-6abd950b5c47)

### Package Version

^2.1

### PHP Version

^8.2

**Comment by maartenpaauw** [comment]
According to the documentation only ‘trial_days’ or ‘has_generic_trial’ can be used **and not both**. ‘trial_days’ leverage stripe trial and ‘has_generic_trial’ leverages database stored trial due date. You have to ship your own logic for generic trials, for example within an observer.
