### ISSUE TITLE
Wrong redirection path

### ISSUE THREAD

**Issue by devhoussam1998** [maartenpaauw/filament-cashier-billing-provider#6]
### What happened?

after I fill the form in checkout page and click on Start Trial button I redirect back to it again it should be redirect to dashboard?

### How to reproduce the bug

I follow all instructions in Laravel Cashier official docs and also README file in this package also my filament multi tenancy setup well.

### Package Version

v1.2.0

### PHP Version

8.1

### Which operating systems does with happen with?

macOS

**Comment by maartenpaauw** [comment]
Did you receive webhook(s) from Stripe and are the subscription and subscription items created within your database?

**Comment by devhoussam1998** [comment]
> Did you receive webhook(s) from Stripe and are the subscription and subscription items created within your database?

yeah I follow the **Laravel Cashier** docs all step are done

**Comment by maartenpaauw** [comment]
And I assume you are using the requiresTenantSubscription method on your panel. What happens when you remove that method? I think there is a race condition. The middleware check is happening before the Stripe webhook is received.

**Comment by maartenpaauw** [comment]
Did you follow the steps in the readme of this package? https://github.com/maartenpaauw/filament-cashier-billing-provider#usage The key `basic` is the name of the subscription. This must match with the subscription you are using. If you didn't specify a subscription name it should be `default`. Thats what Cashier is using.

**Comment by pcfjojo** [comment]
@maartenpaauw 
`return $tenant->redirectToBillingPortal(Dashboard::getUrl());`

Is this correct for redirect url?

**Comment by pcfjojo** [comment]
@maartenpaauw I have been trying to use your package. I did everything as per your readme instructions. 
But it does not work as expected. There is a problem with URL that redirects to the user when the user is not subscribed. 

redirectToBillingPortal(Dashboard::getUrl()) means your are directing to the dashboard page.

**Comment by maartenpaauw** [comment]
@pcfjojo The `Dashboard::getUrl()` generates a URL to the panel dashboard. The Laravel Cashier `->redirectToBillingPortal()` method requires a `return_url`, the user gets returned to the `return_url` after the payment has been done. For more information about the `return_url` see: https://docs.stripe.com/js/payment_intents/confirm_payment#confirm_payment_intent-options-confirmParams-return_url.

The code snippet you are referring to only executes when the user clicks on the `Manage subscription` button within the tenant menu. Are you sure your subscriptions are stored within your local database after you're subscribed?

**Comment by maartenpaauw** [comment]
@pcfjojo If you think it's a real issue, please open a new GitHub with a reproduction repository. This because, I've two applications in production where I don't have the bug you are describing and I can't reproduce it locally.

**Comment by pcfjojo** [comment]
@maartenpaauw Thank you for the reply, I was mising manage subscription menu item.  
now I get an error about 

` Filament tenant does not match the Cashier customer model` 

I think I have to add Billable trait in the team model as well, once I did this test, I let you know :)

**Comment by pcfjojo** [comment]
@maartenpaauw It works. 

Whoever faces  issues like me some tips.

- Team model migration (for cashier)
- Billable Trait in a Team model 
- Change all stripe cashier-based migration to team_id. 
- Also remember ad Tenanct menu for billing management. 

Thanks you.
